const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Category = require('../models/Category');
const Product = require('../models/Product');
const Pincode = require('../models/Pincode');
const Cart = require('../models/Cart');

dotenv.config();

const categoriesData = [
  {
    name: 'Snacks & Namkeen',
    slug: 'snacks-and-namkeen',
    description: 'Crispy, roasted, and traditional savory snacks from Maharashtra.',
    image: 'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
    displayOrder: 1,
  },
  {
    name: 'Spices & Masalas',
    slug: 'spices-and-masalas',
    description: 'Hand-pounded regional spice blends from Vidarbha, Konkan, and Pune.',
    image: 'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
    displayOrder: 2,
  },
  {
    name: 'Pickles & Condiments',
    slug: 'pickles-and-condiments',
    description: 'Authentic homestyle pickles and aromatic spicy chutneys.',
    image: 'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
    displayOrder: 3,
  },
  {
    name: 'Mukhvas & Digestives',
    slug: 'mukhvas-and-digestives',
    description: 'Traditional mouth fresheners, sweet paans, and digestive seeds.',
    image: 'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
    displayOrder: 4,
  },
  {
    name: 'Sweets & Bakery',
    slug: 'sweets-and-bakery',
    description: 'Heritage festive laddoos, pedhas, modaks, and baked teatime delights.',
    image: 'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
    displayOrder: 5,
  },
  {
    name: 'Instant Grocery & Staples',
    slug: 'dry-instant-grocery',
    description: 'Wholesome millet noodles, traditional shengoli, and nourishing soup mixes.',
    image: 'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
    displayOrder: 6,
  },
  {
    name: 'Dairy & Beverages',
    slug: 'dairy-and-beverages',
    description: 'Pure A2 Gir cow ghee, traditional sherbets, and refreshing drinks.',
    image: 'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
    displayOrder: 7,
  },
];

const pincodesData = [
  {
    pincode: '411002',
    city: 'Pune (Shukrawar Peth / Swargate)',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: 'Same Day / 24 Hours',
    expressDelivery: true,
    codAvailable: true,
    deliveryPartner: 'Naik Foods Local Express',
  },
  {
    pincode: '411001',
    city: 'Pune (Camp / Station)',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '24 Hours',
    expressDelivery: true,
    codAvailable: true,
    deliveryPartner: 'Naik Foods Local Express',
  },
  {
    pincode: '411038',
    city: 'Pune (Kothrud)',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '24 Hours',
    expressDelivery: true,
    codAvailable: true,
    deliveryPartner: 'Naik Foods Local Express',
  },
  {
    pincode: '411057',
    city: 'Pune (Wakad / Hinjawadi)',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '24 - 48 Hours',
    expressDelivery: true,
    codAvailable: true,
    deliveryPartner: 'Bluedart Express',
  },
  {
    pincode: '400001',
    city: 'Mumbai (Fort / South Mumbai)',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '1 - 2 Days',
    expressDelivery: true,
    codAvailable: true,
    deliveryPartner: 'Bluedart Surface Air',
  },
  {
    pincode: '400050',
    city: 'Mumbai (Bandra West)',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '1 - 2 Days',
    expressDelivery: true,
    codAvailable: true,
    deliveryPartner: 'Bluedart Surface Air',
  },
  {
    pincode: '440001',
    city: 'Nagpur (Vidarbha Hub)',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '2 - 3 Days',
    expressDelivery: false,
    codAvailable: true,
    deliveryPartner: 'Delhivery Surface',
  },
  {
    pincode: '416001',
    city: 'Kolhapur',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '2 Days',
    expressDelivery: false,
    codAvailable: true,
    deliveryPartner: 'Delhivery Surface',
  },
  {
    pincode: '422001',
    city: 'Nashik',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '2 Days',
    expressDelivery: false,
    codAvailable: true,
    deliveryPartner: 'Delhivery Surface',
  },
  {
    pincode: '431001',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    serviceable: true,
    estimatedDays: '2 - 3 Days',
    expressDelivery: false,
    codAvailable: true,
    deliveryPartner: 'Delhivery Surface',
  },
];

const seedDB = async () => {
  try {
    const connUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/naikfoods';
    console.log(`[Seed Script] Connecting to MongoDB at ${connUri}...`);
    await mongoose.connect(connUri);
    console.log('[Seed Script] Connected to MongoDB');

    // Clear existing collections
    await Promise.all([
      Category.deleteMany({}),
      Product.deleteMany({}),
      Pincode.deleteMany({}),
      Cart.deleteMany({}),
    ]);
    console.log('[Seed Script] Existing collections cleared');

    // 1. Seed Categories
    const createdCategories = await Category.insertMany(categoriesData);
    console.log(`[Seed Script] Seeded ${createdCategories.length} categories`);

    const getCatId = (slug) => {
      const cat = createdCategories.find((c) => c.slug === slug);
      return cat ? cat._id : createdCategories[0]._id;
    };

    // 2. Seed Products
    const productsData = [
      {
        title: 'Multi Millet Noodles',
        slug: 'multi-millet-noodles',
        subtitle: 'Millet Goodness, Crunchy & Wholesome',
        description:
          'Multi Millet Noodles offer a healthier twist on everyday comfort food. Made with an authentic blend of nutritious millets, these noodles deliver great taste, satisfying springy texture, and quick 5-minute preparation without refined flour (Maida).',
        highlights: [
          'Made with Multi Nutritious Millets',
          'Zero Maida & No Preservatives',
          '100% Vegan & Pure Vegetarian',
          'No Onion, No Garlic Friendly',
          'Ready in 5 Minutes',
        ],
        category: getCatId('dry-instant-grocery'),
        categorySlug: 'dry-instant-grocery',
        region: 'Pune',
        dietary: ['Vegan', 'Jain Friendly', 'Millet-Based', 'Zero Maida', '100% Vegetarian'],
        spiceLevel: 'Mild',
        vendor: 'Bchef & Naik Foods',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327380/medusa/1781327380348-pomelli_photoshoot_image_1_1_0612%20%2821%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327380/medusa/1781327380348-pomelli_photoshoot_image_1_1_0612%20%2821%29.png.jpg',
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327380/medusa/1781327380354-pomelli_photoshoot_image_1_1_0612%20%2820%29.png.jpg',
        ],
        ingredients: [
          'Multi Millet Flour Blend (Foxtail, Little, Kodo, Pearl Millet)',
          'Whole Wheat Flour',
          'Cold Pressed Edible Vegetable Oil',
          'Iodized Rock Salt',
          'Natural Roasted Spice Seasoning Mix',
        ],
        shelfLife: '9 Months',
        storageInstruction: 'Store in an airtight container in a cool, dry place away from moisture.',
        variants: [
          {
            variantId: 'v-mmn-180g',
            title: 'Standard Pack (180g)',
            weight: '180g',
            price: 100,
            originalPrice: 120,
            inStock: true,
            inventoryQuantity: 50,
          },
          {
            variantId: 'v-mmn-360g',
            title: 'Value Twin Pack (2 x 180g)',
            weight: '360g',
            price: 185,
            originalPrice: 240,
            inStock: true,
            inventoryQuantity: 40,
          },
          {
            variantId: 'v-mmn-720g',
            title: 'Family Feast Pack (4 x 180g)',
            weight: '720g',
            price: 350,
            originalPrice: 480,
            inStock: true,
            inventoryQuantity: 25,
          },
        ],
        rating: 4.9,
        reviewCount: 38,
        isBestseller: true,
        isFeatured: true,
        reviews: [
          {
            reviewerName: 'Priya Deshmukh',
            rating: 5,
            title: 'Best healthy noodles for kids!',
            comment:
              'My children love Maggi, but switching to this multi-millet alternative was seamless. The taste is genuine and texture is nice and springy without feeling rubbery.',
            verifiedPurchase: true,
            date: new Date('2026-08-15'),
          },
          {
            reviewerName: 'Rohan Joshi',
            rating: 5,
            title: 'Zero guilt evening snack',
            comment:
              'No maida, no artificial MSG. Excellent seasoning packet included. Highly recommended for Pune techies!',
            verifiedPurchase: true,
            date: new Date('2026-08-28'),
          },
        ],
      },
      {
        title: 'Pearl Millet (Bajra) Noodles',
        slug: 'pearl-millet-noodles',
        subtitle: 'Bajra Rich, Wholesome & Light on Stomach',
        description:
          'Pearl Millet Noodles bring together the rustic power of Bajra and the modern convenience of noodles. Naturally rich in dietary fiber, iron, and slow-burning complex carbs, crafted according to Maharashtrian agricultural traditions.',
        highlights: [
          'High Fiber Pearl Millet (Bajra)',
          'Zero Maida & Gluten-Conscious',
          'Rich in Iron & Essential Minerals',
          '100% Vegetarian Snack',
          'Cooks in Under 5 Minutes',
        ],
        category: getCatId('dry-instant-grocery'),
        categorySlug: 'dry-instant-grocery',
        region: 'Pune',
        dietary: ['Millet-Based', 'Zero Maida', '100% Vegetarian'],
        spiceLevel: 'Mild',
        vendor: 'Millet Bank',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328453/medusa/1781328451789-pomelli_photoshoot_image_1_1_0612%20%2811%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328453/medusa/1781328451789-pomelli_photoshoot_image_1_1_0612%20%2811%29.png.jpg',
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328453/medusa/1781328451797-pomelli_photoshoot_image_1_1_0612%20%2810%29.png.jpg',
        ],
        ingredients: [
          'Pure Pearl Millet (Bajra) Flour',
          'Whole Wheat Meal',
          'Cold Pressed Sunflower Oil',
          'Iodized Salt',
          'Natural Spices Blend',
        ],
        shelfLife: '9 Months',
        storageInstruction: 'Keep away from direct heat and sunlight.',
        variants: [
          {
            variantId: 'v-pmn-180g',
            title: 'Single Pack (180g)',
            weight: '180g',
            price: 120,
            originalPrice: 140,
            inStock: true,
            inventoryQuantity: 45,
          },
          {
            variantId: 'v-pmn-360g',
            title: 'Twin Pack (360g)',
            weight: '360g',
            price: 220,
            originalPrice: 280,
            inStock: true,
            inventoryQuantity: 30,
          },
        ],
        rating: 4.8,
        reviewCount: 24,
        isBestseller: false,
        isFeatured: true,
        reviews: [
          {
            reviewerName: 'Sunita Kulkarni',
            rating: 5,
            title: 'Authentic Bajra taste',
            comment: 'Reminds me of traditional Bajra bhakri flavors, but in a very handy noodle format. Very filling.',
            verifiedPurchase: true,
            date: new Date('2026-08-10'),
          },
        ],
      },
      {
        title: 'Foxtail Millet Noodles',
        slug: 'foxtail-millet-noodles',
        subtitle: 'Light, Easy to Digest & Energizing',
        description:
          'Foxtail Millet (Kangni / Rala) noodles are celebrated in Ayurvedic nutrition for their balanced glycemic index and gentle digestion. Seasoned with authentic Maharashtrian spices for an irresistible hot bowl.',
        highlights: [
          'Pure Foxtail Millet (Rala) Flour',
          'Zero Preservatives & Zero Trans-fat',
          'Low Glycemic Index Grain',
          'Quick Cooking in 5 Minutes',
          '100% Vegan',
        ],
        category: getCatId('dry-instant-grocery'),
        categorySlug: 'dry-instant-grocery',
        region: 'Pune',
        dietary: ['Vegan', 'Millet-Based', 'Zero Maida', '100% Vegetarian'],
        spiceLevel: 'Medium',
        vendor: 'Bchef',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328909/medusa/1781328907725-pomelli_photoshoot_image_1_1_0612%20%287%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328909/medusa/1781328907725-pomelli_photoshoot_image_1_1_0612%20%287%29.png.jpg',
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328909/medusa/1781328907733-pomelli_photoshoot_image_1_1_0612%20%286%29.png.jpg',
        ],
        ingredients: [
          'Foxtail Millet Flour',
          'Whole Wheat Flour',
          'Edible Oil',
          'Himalayan Pink Salt',
          'Turmeric & Pepper Blend',
        ],
        shelfLife: '9 Months',
        storageInstruction: 'Store in dry pantry.',
        variants: [
          {
            variantId: 'v-fmn-180g',
            title: '180g Pack',
            weight: '180g',
            price: 110,
            originalPrice: 130,
            inStock: true,
            inventoryQuantity: 50,
          },
          {
            variantId: 'v-fmn-360g',
            title: '360g Twin Pack',
            weight: '360g',
            price: 200,
            originalPrice: 260,
            inStock: true,
            inventoryQuantity: 35,
          },
        ],
        rating: 4.7,
        reviewCount: 19,
        isBestseller: false,
        isFeatured: false,
        reviews: [],
      },
      {
        title: 'Jowar Palak Khakhra',
        slug: 'jowar-palak-khakhra',
        subtitle: 'Roasted Sorghum & Fresh Farm Spinach Crunch',
        description:
          'Jowar Palak Khakhra is masterfully roasted using stone-ground Jowar and pureed fresh spinach leaves. Extra thin, exceptionally crispy, and packed with homestyle spices. Perfect teatime snack without oiliness.',
        highlights: [
          'Stone-Ground Jowar & Spinach Leaves',
          'Slow Roasted on Traditional Tawa',
          'Zero Maida & Low Oil Content',
          'Rich in Iron & Fiber',
          '100% Jain Friendly Recipe',
        ],
        category: getCatId('snacks-and-namkeen'),
        categorySlug: 'snacks-and-namkeen',
        region: 'Pune',
        dietary: ['Vegan', 'Jain Friendly', 'Millet-Based', 'Zero Maida', '100% Vegetarian'],
        spiceLevel: 'Mild',
        vendor: 'Healthgram',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329341/medusa/1781329339472-pomelli_photoshoot_image_1_1_0612%20%2813%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329341/medusa/1781329339472-pomelli_photoshoot_image_1_1_0612%20%2813%29.png.jpg',
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329341/medusa/1781329339504-pomelli_photoshoot_image_1_1_0612%20%2812%29.png.jpg',
        ],
        ingredients: [
          'Jowar (Sorghum) Flour',
          'Whole Wheat Flour',
          'Fresh Spinach (Palak) Puree',
          'Sunflower Oil',
          'Sesame Seeds (Til)',
          'Ajwain',
          'Iodized Salt',
        ],
        shelfLife: '6 Months',
        storageInstruction: 'Store in airtight tin or box after opening seal.',
        variants: [
          {
            variantId: 'v-jpk-200g',
            title: 'Standard Pack (200g)',
            weight: '200g',
            price: 130,
            originalPrice: 150,
            inStock: true,
            inventoryQuantity: 60,
          },
          {
            variantId: 'v-jpk-400g',
            title: 'Twin Pack (400g)',
            weight: '400g',
            price: 240,
            originalPrice: 300,
            inStock: true,
            inventoryQuantity: 40,
          },
        ],
        rating: 4.9,
        reviewCount: 42,
        isBestseller: true,
        isFeatured: true,
        reviews: [
          {
            reviewerName: 'Neeta Patwardhan',
            rating: 5,
            title: 'Crispy and wholesome!',
            comment:
              'Very crisp and aromatic. Love the spinach and ajwain combination. Excellent quality from Naik Foods store.',
            verifiedPurchase: true,
            date: new Date('2026-08-20'),
          },
        ],
      },
      {
        title: 'Chorafali Khakhra',
        slug: 'chorafali-khakhra',
        subtitle: 'Authentic Fluffy Spiced Crispy Delight',
        description:
          'Inspired by traditional festive Chorafali, this thin roasted khakhra is seasoned with dry mango powder (amchur), black salt, and fragrant red chili blend. Delivers a melt-in-mouth tangy crunch.',
        highlights: [
          'Crafted from Besan & Urad Flour Blend',
          'Tangy Masala Dusting',
          'Light & Crispy Wafer Thin Texture',
          'No Artificial Flavors or Colors',
          'Teatime Bestseller',
        ],
        category: getCatId('snacks-and-namkeen'),
        categorySlug: 'snacks-and-namkeen',
        region: 'Pune',
        dietary: ['Vegan', 'Zero Maida', '100% Vegetarian'],
        spiceLevel: 'Medium',
        vendor: 'Healthgram',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329714/medusa/1781329712422-pomelli_photoshoot_image_1_1_0612%20%283%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329714/medusa/1781329712422-pomelli_photoshoot_image_1_1_0612%20%283%29.png.jpg',
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329714/medusa/1781329712431-pomelli_photoshoot_image_1_1_0612%20%282%29.png.jpg',
        ],
        ingredients: [
          'Chana & Urad Dal Flour',
          'Sunflower Oil',
          'Black Salt (Kala Namak)',
          'Dry Mango Powder (Amchur)',
          'Red Chili Powder',
          'Asafoetida (Hing)',
        ],
        shelfLife: '6 Months',
        storageInstruction: 'Keep sealed.',
        variants: [
          {
            variantId: 'v-ck-200g',
            title: 'Standard Pack (200g)',
            weight: '200g',
            price: 130,
            originalPrice: 150,
            inStock: true,
            inventoryQuantity: 55,
          },
          {
            variantId: 'v-ck-400g',
            title: 'Twin Pack (400g)',
            weight: '400g',
            price: 240,
            originalPrice: 300,
            inStock: true,
            inventoryQuantity: 30,
          },
        ],
        rating: 4.8,
        reviewCount: 31,
        isBestseller: true,
        isFeatured: false,
        reviews: [],
      },
      {
        title: 'Bajra Methi Khakhra',
        slug: 'bajra-methi-khakhra',
        subtitle: 'Roasted Bajra with Sun-Dried Methi Leaves',
        description:
          'A winter and monsoon heritage classic in western Maharashtra. Prepared with wholesome bajra flour and fragrant sun-dried fenugreek leaves (methi) roasted to perfection.',
        highlights: [
          'Nutrient-Dense Pearl Millet Base',
          'Infused with Real Kasuri Methi',
          'Slow Roasted on Cast Iron Tawas',
          'Zero Added Preservatives',
          'Pure Comfort Teatime Snack',
        ],
        category: getCatId('snacks-and-namkeen'),
        categorySlug: 'snacks-and-namkeen',
        region: 'Pune',
        dietary: ['Vegan', 'Millet-Based', 'Zero Maida', '100% Vegetarian'],
        spiceLevel: 'Mild',
        vendor: 'Healthgram',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329385/medusa/1781329383405-pomelli_photoshoot_image_1_1_0612%20%285%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329385/medusa/1781329383405-pomelli_photoshoot_image_1_1_0612%20%285%29.png.jpg',
        ],
        ingredients: [
          'Bajra Flour',
          'Whole Wheat Flour',
          'Fenugreek Leaves (Methi)',
          'Green Chili',
          'Turmeric',
          'Salt',
          'Sesame',
        ],
        shelfLife: '6 Months',
        storageInstruction: 'Store in dry place.',
        variants: [
          {
            variantId: 'v-bmk-200g',
            title: '200g Pack',
            weight: '200g',
            price: 130,
            originalPrice: 150,
            inStock: true,
            inventoryQuantity: 40,
          },
        ],
        rating: 4.7,
        reviewCount: 18,
        isBestseller: false,
        isFeatured: false,
        reviews: [],
      },
      {
        title: 'Aaswad Mitha Paan',
        slug: 'aaswad-mitha-paan',
        subtitle: 'Authentic Sweet Paan Flavor in Every Scoop',
        description:
          'Aaswad Mitha Paan captures the authentic sweet paan tradition of Maharashtra. Blended with real betel leaf flakes, aromatic gulkand (rose petal preserve), fennel seeds, cardamom, and natural cooling menthol.',
        highlights: [
          'Real Betel Leaf Flakes & Gulkand',
          '100% Tobacco-Free & Supari-Free',
          'Digestive & Palate Cleanser',
          'Rich Rose & Cardamom Aroma',
          'Ideal Post-Meal Hospitality Treat',
        ],
        category: getCatId('mukhvas-and-digestives'),
        categorySlug: 'mukhvas-and-digestives',
        region: 'Pune',
        dietary: ['100% Vegetarian'],
        spiceLevel: 'None',
        vendor: 'Anushka Munchings',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328014/medusa/1781328012514-pomelli_photoshoot_image_1_1_0612%20%2815%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328014/medusa/1781328012514-pomelli_photoshoot_image_1_1_0612%20%2815%29.png.jpg',
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328014/medusa/1781328012520-pomelli_photoshoot_image_1_1_0612%20%2814%29.png.jpg',
        ],
        ingredients: [
          'Sweet Fennel Seeds',
          'Betel Leaves (Nagarvel Paan)',
          'Gulkand (Organic Rose Petal Jam)',
          'Cardamom (Elaichi)',
          'Coriander Splits (Dhana Dal)',
          'Menthol Essence',
        ],
        shelfLife: '12 Months',
        storageInstruction: 'Store in cool ambient conditions. Keep lid tightly closed.',
        variants: [
          {
            variantId: 'v-amp-100g',
            title: 'Pouch (100g)',
            weight: '100g',
            price: 110,
            originalPrice: 130,
            inStock: true,
            inventoryQuantity: 80,
          },
          {
            variantId: 'v-amp-250g',
            title: 'Jar Pack (250g)',
            weight: '250g',
            price: 240,
            originalPrice: 290,
            inStock: true,
            inventoryQuantity: 50,
          },
        ],
        rating: 4.9,
        reviewCount: 52,
        isBestseller: true,
        isFeatured: true,
        reviews: [
          {
            reviewerName: 'Amit Sane',
            rating: 5,
            title: 'Best mitha paan without supari',
            comment:
              'Tastes exactly like the authentic Pune paan without any artificial or harsh ingredients. My parents love it after dinner!',
            verifiedPurchase: true,
            date: new Date('2026-08-25'),
          },
        ],
      },
      {
        title: 'Shahi Mukhwas',
        slug: 'shahi-mukhwas',
        subtitle: 'Royal Blend of Roasted Seeds & Rose Petals',
        description:
          'A royal after-meal mukhwas crafted with roasted fennel seeds, toasted sesame, crunchy dhana dal, and sweet aromatic sugar pearls. Clean, fresh, and exceptionally satisfying crunch.',
        highlights: [
          'Royal Blend of 7 Digestive Seeds',
          'Crunchy Toasted Dhana Dal & Til',
          'Sweet Aromatic Finish',
          'Aids Gentle Digestion',
          'Traditional Pune Hospitality Recipe',
        ],
        category: getCatId('mukhvas-and-digestives'),
        categorySlug: 'mukhvas-and-digestives',
        region: 'Pune',
        dietary: ['100% Vegetarian'],
        spiceLevel: 'None',
        vendor: 'Anushka Munchings',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327582/medusa/1781327580352-pomelli_photoshoot_image_1_1_0612%20%2819%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327582/medusa/1781327580352-pomelli_photoshoot_image_1_1_0612%20%2819%29.png.jpg',
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327582/medusa/1781327580361-pomelli_photoshoot_image_1_1_0612%20%2818%29.png.jpg',
        ],
        ingredients: [
          'Roasted Fennel (Saunf)',
          'White Sesame Seeds (Til)',
          'Coriander Splits (Dhana Dal)',
          'Watermelon Seeds',
          'Dry Coconut Flakes',
          'Sugar Sprinkles',
          'Natural Mint Oil',
        ],
        shelfLife: '12 Months',
        storageInstruction: 'Store in a dry glass or pet jar.',
        variants: [
          {
            variantId: 'v-sm-100g',
            title: 'Pouch (100g)',
            weight: '100g',
            price: 100,
            originalPrice: 120,
            inStock: true,
            inventoryQuantity: 70,
          },
          {
            variantId: 'v-sm-250g',
            title: 'Jar Pack (250g)',
            weight: '250g',
            price: 220,
            originalPrice: 260,
            inStock: true,
            inventoryQuantity: 45,
          },
        ],
        rating: 4.8,
        reviewCount: 29,
        isBestseller: false,
        isFeatured: false,
        reviews: [],
      },
      {
        title: 'Authentic Vidarbha Goda Masala',
        slug: 'vidarbha-goda-masala',
        subtitle: 'Traditional Hand-Pounded Black Spice Blend',
        description:
          'Goda Masala is the crown jewel of Maharashtrian kitchens. Hand-pounded in Vidarbha using slow-roasted whole spices, dagad phool (stone flower), coconut, and sesame, yielding its signature deep dark color and sweet aromatic warmth.',
        highlights: [
          'Authentic Vidarbha Hand-Pounded Recipe',
          'Contains Rare Stone Flower (Dagad Phool)',
          'Slow-Roasted with Pure Cold-Pressed Oil',
          'Essential for Amti, Bharli Vangi & Katachi Amti',
          'No Added Fillers or Artificial Colors',
        ],
        category: getCatId('spices-and-masalas'),
        categorySlug: 'spices-and-masalas',
        region: 'Vidarbha',
        dietary: ['Vegan', '100% Vegetarian'],
        spiceLevel: 'Medium',
        vendor: 'Naik Foods Heritage',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
        ],
        ingredients: [
          'Coriander Seeds (Dhana)',
          'Cumin Seeds (Jeera)',
          'White Sesame (Til)',
          'Dry Coconut (Khobara)',
          'Dagad Phool (Stone Flower)',
          'Cinnamon, Cloves & Star Anise',
          'Nagkeshar & Bay Leaf',
        ],
        shelfLife: '12 Months',
        storageInstruction: 'Store in clean, dry glass jar to preserve aroma.',
        variants: [
          {
            variantId: 'v-gm-100g',
            title: 'Pouch (100g)',
            weight: '100g',
            price: 120,
            originalPrice: 140,
            inStock: true,
            inventoryQuantity: 65,
          },
          {
            variantId: 'v-gm-250g',
            title: 'Value Pack (250g)',
            weight: '250g',
            price: 275,
            originalPrice: 320,
            inStock: true,
            inventoryQuantity: 45,
          },
          {
            variantId: 'v-gm-500g',
            title: 'Kitchen Master Pack (500g)',
            weight: '500g',
            price: 520,
            originalPrice: 620,
            inStock: true,
            inventoryQuantity: 20,
          },
        ],
        rating: 5.0,
        reviewCount: 64,
        isBestseller: true,
        isFeatured: true,
        reviews: [
          {
            reviewerName: 'Radhika Savarkar',
            rating: 5,
            title: 'The aroma when opening the bag is incredible!',
            comment:
              'My grandmother used to make Goda Masala like this in Nagpur. The stone flower and roasted coconut fragrance is 100% authentic.',
            verifiedPurchase: true,
            date: new Date('2026-07-14'),
          },
        ],
      },
      {
        title: 'Konkani Coconut Fish & Curry Masala',
        slug: 'konkani-curry-masala',
        subtitle: 'Coastal Malvan & Konkan Signature Spice Blend',
        description:
          'From the sun-soaked coastline of Konkan and Sindhudurg, this authentic Malvani curry masala is crafted using Bedgi chilies, star anise, triphala, and fragrant coastal spices. Elevates both seafood and rustic vegetarian curries.',
        highlights: [
          'Authentic Konkan Coastal Spices',
          'Rich Bedgi Chili Hue & Fiery Aroma',
          'Contains Wild Triphala (Sichuan Pepper cousin)',
          'Perfect for Malvani Curries & Ushals',
        ],
        category: getCatId('spices-and-masalas'),
        categorySlug: 'spices-and-masalas',
        region: 'Konkan',
        dietary: ['Vegan', '100% Vegetarian'],
        spiceLevel: 'Spicy',
        vendor: 'Naik Foods Heritage',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
        ],
        ingredients: [
          'Bedgi & Sankeshwari Dry Red Chilies',
          'Coriander & Cumin',
          'Triphala (Konkan Berry)',
          'Black Pepper & Cloves',
          'Turmeric & Mace',
        ],
        shelfLife: '12 Months',
        storageInstruction: 'Store in cool, dry place away from steam.',
        variants: [
          {
            variantId: 'v-kcm-100g',
            title: '100g Pack',
            weight: '100g',
            price: 130,
            originalPrice: 150,
            inStock: true,
            inventoryQuantity: 40,
          },
          {
            variantId: 'v-kcm-250g',
            title: '250g Pack',
            weight: '250g',
            price: 280,
            originalPrice: 340,
            inStock: true,
            inventoryQuantity: 30,
          },
        ],
        rating: 4.9,
        reviewCount: 27,
        isBestseller: false,
        isFeatured: true,
        reviews: [],
      },
      {
        title: 'Authentic Puneri Bakarwadi',
        slug: 'puneri-bakarwadi',
        subtitle: 'Spiral Crispy Crust with Sweet, Tangy & Spicy Core',
        description:
          'Pune’s most famous teatime delicacy. Golden crispy gram flour rolls packed with a mouthwatering filling of toasted poppy seeds (khus khus), dry coconut, tamarind paste, and selected spices. Crispy, spicy, and irresistible.',
        highlights: [
          'Classic Pune Chitale-Style Spiral Bakarwadi',
          'Tangy Tamarind & Khus Khus Masala Filling',
          'Crunchy Outer Crust without Excess Greasiness',
          'Freshly Prepared Daily in Shukrawar Peth',
          'No Artificial Preservatives',
        ],
        category: getCatId('snacks-and-namkeen'),
        categorySlug: 'snacks-and-namkeen',
        region: 'Pune',
        dietary: ['100% Vegetarian'],
        spiceLevel: 'Medium',
        vendor: 'Naik Foods Heritage',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329714/medusa/1781329712422-pomelli_photoshoot_image_1_1_0612%20%283%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781329714/medusa/1781329712422-pomelli_photoshoot_image_1_1_0612%20%283%29.png.jpg',
        ],
        ingredients: [
          'Gram Flour (Besan)',
          'Refined Wheat Flour',
          'Edible Vegetable Oil',
          'Dry Coconut',
          'Poppy Seeds (Khus Khus)',
          'Tamarind',
          'Sesame',
          'Coriander & Spices',
        ],
        shelfLife: '3 Months',
        storageInstruction: 'Store in an airtight container.',
        variants: [
          {
            variantId: 'v-pb-250g',
            title: 'Pouch (250g)',
            weight: '250g',
            price: 95,
            originalPrice: 110,
            inStock: true,
            inventoryQuantity: 90,
          },
          {
            variantId: 'v-pb-500g',
            title: 'Standard Box (500g)',
            weight: '500g',
            price: 180,
            originalPrice: 220,
            inStock: true,
            inventoryQuantity: 60,
          },
        ],
        rating: 5.0,
        reviewCount: 78,
        isBestseller: true,
        isFeatured: true,
        reviews: [
          {
            reviewerName: 'Gaurav Kadam',
            rating: 5,
            title: 'Top notch crunch!',
            comment:
              'Always ordered when visiting Pune, now thrilled to have it shipped fresh to Mumbai. Fresh and perfectly spiced.',
            verifiedPurchase: true,
            date: new Date('2026-08-01'),
          },
        ],
      },
      {
        title: 'Kolhapuri Thecha (Mirchi Kharda)',
        slug: 'kolhapuri-thecha',
        subtitle: 'Fiery Coarse-Crushed Green Chili & Garlic Relish',
        description:
          'Kolhapur’s famous rustic condiment. Spicy green chillies, golden-roasted garlic cloves, cumin, and sea salt coarse-crushed on stone mortar (Pata-Varvanta) with cold-pressed peanut oil.',
        highlights: [
          'Authentic Stone-Crushed Kolhapuri Recipe',
          'Fiery Spicy Kick (Teekha)',
          'Made with Cold Pressed Groundnut Oil',
          'Perfect Partner for Jowar Bhakri & Pithla',
        ],
        category: getCatId('pickles-and-condiments'),
        categorySlug: 'pickles-and-condiments',
        region: 'Western Maharashtra',
        dietary: ['Vegan', '100% Vegetarian'],
        spiceLevel: 'Kolhapuri Teekha',
        vendor: 'Naik Foods Heritage',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1775205758/SVG_1_y89cdr.svg',
        ],
        ingredients: [
          'Fresh Green Lavangi Chillies',
          'Fresh Garlic Pods',
          'Roasted Peanuts',
          'Cold Pressed Groundnut Oil',
          'Cumin Seeds',
          'Rock Salt',
        ],
        shelfLife: '4 Months',
        storageInstruction: 'Refrigerate after opening.',
        variants: [
          {
            variantId: 'v-kt-150g',
            title: 'Jar (150g)',
            weight: '150g',
            price: 110,
            originalPrice: 130,
            inStock: true,
            inventoryQuantity: 50,
          },
          {
            variantId: 'v-kt-300g',
            title: 'Value Jar (300g)',
            weight: '300g',
            price: 200,
            originalPrice: 240,
            inStock: true,
            inventoryQuantity: 35,
          },
        ],
        rating: 4.9,
        reviewCount: 45,
        isBestseller: true,
        isFeatured: false,
        reviews: [],
      },
      {
        title: 'Hulage (Kulith) Shengoli',
        slug: 'hulage-kulith-shengoli',
        subtitle: 'Rustic Maharashtrian Horse Gram Delicacy',
        description:
          'Hulage (Kulith / Horse Gram) Shengoli is a treasured rural Maharashtrian superfood. Naturally high in protein, iron, and warming qualities, this ready-to-cook preparation brings the village kitchen flavors to your home.',
        highlights: [
          'Premium Horse Gram (Kulith) Nutrition',
          'Traditional Handcrafted Shape',
          'Warming Comfort Food for Monsoons & Winters',
          'High Plant Protein & Dietary Iron',
        ],
        category: getCatId('dry-instant-grocery'),
        categorySlug: 'dry-instant-grocery',
        region: 'Western Maharashtra',
        dietary: ['Vegan', 'Zero Maida', '100% Vegetarian'],
        spiceLevel: 'Mild',
        vendor: 'Naik Foods Heritage',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327380/medusa/1781327380348-pomelli_photoshoot_image_1_1_0612%20%2821%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781327380/medusa/1781327380348-pomelli_photoshoot_image_1_1_0612%20%2821%29.png.jpg',
        ],
        ingredients: [
          'Kulith (Horse Gram) Flour',
          'Whole Wheat Flour',
          'Ajwain',
          'Garlic & Chili Paste',
          'Sesame Seeds',
          'Salt',
        ],
        shelfLife: '6 Months',
        storageInstruction: 'Store in dry place.',
        variants: [
          {
            variantId: 'v-hks-250g',
            title: 'Pack (250g)',
            weight: '250g',
            price: 140,
            originalPrice: 160,
            inStock: true,
            inventoryQuantity: 30,
          },
        ],
        rating: 4.8,
        reviewCount: 15,
        isBestseller: false,
        isFeatured: false,
        reviews: [],
      },
      {
        title: 'Baba Jadhav Shevga Drumstick Soup Mix',
        slug: 'baba-jadhav-shevga-soup',
        subtitle: 'Warm, Nourishing Drumstick & Moringa Soup',
        description:
          'Crafted with real drumstick (shevga) pulp and sun-dried moringa leaves. A quick, warm, and comforting bowl filled with ancient wellness nutrients for evenings and cold weather.',
        highlights: [
          'Real Drumstick (Shevga) & Moringa Leaf Powder',
          'Ayurvedic Wellness & Immunity Support',
          'Instant 2-Minute Preparation in Boiling Water',
          'Zero Corn Starch & No Artificial Flavors',
        ],
        category: getCatId('dry-instant-grocery'),
        categorySlug: 'dry-instant-grocery',
        region: 'Western Maharashtra',
        dietary: ['Vegan', 'Gluten-Free', '100% Vegetarian'],
        spiceLevel: 'Mild',
        vendor: 'Baba Jadhav Organics',
        thumbnail:
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328909/medusa/1781328907725-pomelli_photoshoot_image_1_1_0612%20%287%29.png.jpg',
        images: [
          'https://res.cloudinary.com/dskzfipt3/image/upload/v1781328909/medusa/1781328907725-pomelli_photoshoot_image_1_1_0612%20%287%29.png.jpg',
        ],
        ingredients: [
          'Drumstick (Shevga) Pulp Powder',
          'Moringa Leaf Powder',
          'Black Pepper',
          'Roasted Cumin',
          'Ginger Powder',
          'Pink Himalayan Salt',
        ],
        shelfLife: '9 Months',
        storageInstruction: 'Store in cool, dry place.',
        variants: [
          {
            variantId: 'v-bjs-100g',
            title: 'Pack of 5 Servings (100g)',
            weight: '100g',
            price: 150,
            originalPrice: 175,
            inStock: true,
            inventoryQuantity: 40,
          },
        ],
        rating: 4.9,
        reviewCount: 22,
        isBestseller: false,
        isFeatured: true,
        reviews: [],
      },
    ];

    const createdProducts = await Product.insertMany(productsData);
    console.log(`[Seed Script] Seeded ${createdProducts.length} authentic products`);

    // 3. Seed Pincodes
    const createdPincodes = await Pincode.insertMany(pincodesData);
    console.log(`[Seed Script] Seeded ${createdPincodes.length} pincodes for delivery checking`);

    console.log('[Seed Script] Database successfully seeded with authentic Naik Foods catalog!');
    process.exit(0);
  } catch (error) {
    console.error('[Seed Script Error]:', error);
    process.exit(1);
  }
};

seedDB();
